import * as react from "react";
import { useState } from "react";
import { z } from "zod";
import { supabase } from "../lib/supabase";

// Define the form schema with validation rules
const contactFormSchema = z.object({
	name: z.string().min(1, { message: "Name is required" }),
	email: z.string().email({ message: "Please enter a valid email address" }),
	message: z
		.string()
		.min(10, { message: "Message must be at least 10 characters long" }),
});

type ContactFormData = z.infer<typeof contactFormSchema>;

export const ContactPage: react.FC = () => {
	const [formData, setFormData] = useState<ContactFormData>({
		name: "",
		email: "",
		message: "",
	});
	const [formErrors, setFormErrors] = useState<Record<string, string>>({});
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [submitStatus, setSubmitStatus] = useState<{
		success: boolean;
		message: string;
	} | null>(null);

	const handleChange = (
		e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
	) => {
		const { name, value } = e.target;
		setFormData(prev => ({
			...prev,
			[name]: value,
		}));
	};

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();

		// Validate form data
		const validationResult = contactFormSchema.safeParse(formData);

		if (!validationResult.success) {
			// Convert Zod errors to a more usable format
			const errors: Record<string, string> = {};
			validationResult.error.errors.forEach(err => {
				if (err.path) {
					errors[err.path[0]] = err.message;
				}
			});
			setFormErrors(errors);
			return;
		}

		// Clear any previous errors
		setFormErrors({});
		setIsSubmitting(true);
		setSubmitStatus(null);

		try {
			const { error } = await supabase.from("contact").insert([
				{
					name: formData.name,
					email: formData.email,
					message: formData.message,
					// id and created_at will be automatically generated by the database
					// status will default to 'unread' as per the table definition
				},
			]);

			if (error) throw error;

			setSubmitStatus({
				success: true,
				message:
					"Your message has been received! We'll get back to you soon.",
			});
			setFormData({ name: "", email: "", message: "" }); // Reset form
		} catch (error) {
			console.error("Failed to save message:", error);
			setSubmitStatus({
				success: false,
				message: "Failed to send message. Please try again later.",
			});
		} finally {
			setIsSubmitting(false);
		}
	};

	return (
		<div className="fade-in bg-[#096B68]" id="contact">
			<section className="py-20">
				<div className="container mx-auto px-6">
					<div className="max-w-2xl mx-auto bg-[#129990] p-8 rounded-lg shadow-lg text-[#FFFBDE]">
						<h1 className="text-4xl font-bold text-center mb-8">
							Contact Us
						</h1>
						<p className="text-center mb-8">
							We'd love to hear from you. Please fill out the form
							below to get in touch.
						</p>

						{submitStatus && (
							<div
								className={`mb-6 p-4 rounded-lg ${
									submitStatus.success
										? "bg-green-200 text-green-900"
										: "bg-red-200 text-red-900"
								}`}>
								{submitStatus.message}
							</div>
						)}

						<form onSubmit={handleSubmit} className="space-y-6">
							<div>
								<label
									htmlFor="name"
									className="block font-bold mb-2">
									Name
								</label>
								<input
									type="text"
									id="name"
									name="name"
									value={formData.name}
									onChange={handleChange}
									className={`w-full px-4 py-2 border rounded-lg bg-[#FFFBDE] text-gray-800 border-[#0d7a73] focus:outline-none focus:ring-2 focus:ring-[#FFFBDE] ${
										formErrors.name ? "border-red-500" : ""
									}`}
									disabled={isSubmitting}
								/>
								{formErrors.name && (
									<p className="text-red-300 text-sm mt-1">
										{formErrors.name}
									</p>
								)}
							</div>
							<div>
								<label
									htmlFor="email"
									className="block font-bold mb-2">
									Email
								</label>
								<input
									type="email"
									id="email"
									name="email"
									value={formData.email}
									onChange={handleChange}
									className={`w-full px-4 py-2 border rounded-lg bg-[#FFFBDE] text-gray-800 border-[#0d7a73] focus:outline-none focus:ring-2 focus:ring-[#FFFBDE] ${
										formErrors.email ? "border-red-500" : ""
									}`}
									disabled={isSubmitting}
								/>
								{formErrors.email && (
									<p className="text-red-300 text-sm mt-1">
										{formErrors.email}
									</p>
								)}
							</div>
							<div>
								<label
									htmlFor="message"
									className="block font-bold mb-2">
									Message
								</label>
								<textarea
									id="message"
									name="message"
									value={formData.message}
									onChange={handleChange}
									rows={5}
									className={`w-full px-4 py-2 border rounded-lg bg-[#FFFBDE] text-gray-800 border-[#0d7a73] focus:outline-none focus:ring-2 focus:ring-[#FFFBDE] ${
										formErrors.message
											? "border-red-500"
											: ""
									}`}
									disabled={isSubmitting}></textarea>
								{formErrors.message && (
									<p className="text-red-300 text-sm mt-1">
										{formErrors.message}
									</p>
								)}
							</div>
							<div className="text-center">
								<button
									type="submit"
									disabled={isSubmitting}
									className={`inline-block font-bold py-3 px-8 text-lg rounded-full transition-all duration-300 ease-in-out transform shadow-md hover:shadow-lg hover:-translate-y-1 ${
										isSubmitting
											? "bg-gray-400 text-gray-800 cursor-not-allowed"
											: "bg-[#FFFBDE] hover:bg-opacity-90 text-[#096B68]"
									}`}>
									{isSubmitting
										? "Sending..."
										: "Send Message"}
								</button>
							</div>
						</form>
					</div>
				</div>
			</section>
		</div>
	);
};
